import { Event, Organizer, ScheduleSlot } from "./types";

export const DUMMY_EVENTS: Omit<Event, "id">[] = [
  {
    name: "Code Clash",
    description: "Competitive programming challenge. Solve algorithmic problems under time pressure. Individual or team participation.",
    category: "tech",
    minTeamSize: 1,
    maxTeamSize: 2,
    isActive: true,
    icon: "Code",
    rules: ["Languages: C, C++, Java, Python", "No internet access during contest", "90-minute time limit"],
  },
  {
    name: "Web Wizards",
    description: "Build a stunning website from scratch in 3 hours. Theme revealed on spot. Creativity and functionality both count.",
    category: "tech",
    minTeamSize: 1,
    maxTeamSize: 3,
    isActive: true,
    icon: "Globe",
    rules: ["No templates or pre-built code", "Must use HTML/CSS/JS minimum", "Frameworks allowed"],
  },
  {
    name: "Debug Duals",
    description: "Find and fix bugs in provided code snippets. Speed and accuracy matter. Test your debugging skills.",
    category: "tech",
    minTeamSize: 1,
    maxTeamSize: 2,
    isActive: true,
    icon: "Bug",
    rules: ["Multiple languages", "Points for speed", "Partial fixes count"],
  },
  {
    name: "Circuit Quest",
    description: "Design and build electronic circuits to solve real-world problems. Components provided on spot.",
    category: "hardware",
    minTeamSize: 2,
    maxTeamSize: 3,
    isActive: true,
    icon: "Cpu",
    rules: ["Basic components provided", "Breadboard-based prototyping", "Working demo required"],
  },
  {
    name: "Robo Race",
    description: "Build a bot and race it through an obstacle course. Speed, agility, and engineering excellence tested.",
    category: "hardware",
    minTeamSize: 2,
    maxTeamSize: 4,
    isActive: true,
    icon: "Bot",
    rules: ["Bot dimensions: max 30×30 cm", "Wireless control required", "3 attempts per team"],
  },
  {
    name: "Valorant Showdown",
    description: "5v5 Valorant tournament. Show your aim, strategy, and teamwork. Bracket-style elimination.",
    category: "gaming",
    minTeamSize: 5,
    maxTeamSize: 5,
    isActive: true,
    icon: "Gamepad2",
    rules: ["Bring your own peripherals", "PC provided", "Standard competitive rules"],
  },
  {
    name: "BGMI Battle",
    description: "Battle Royale BGMI tournament. Squad mode. Last team standing wins the crown.",
    category: "gaming",
    minTeamSize: 4,
    maxTeamSize: 4,
    isActive: true,
    icon: "Smartphone",
    rules: ["Bring your own device", "Emulators not allowed", "Fair play policy enforced"],
  },
  {
    name: "UI/UX Challenge",
    description: "Design a mobile app UI for a given problem statement. Figma or any design tool allowed.",
    category: "creative",
    minTeamSize: 1,
    maxTeamSize: 2,
    isActive: true,
    icon: "Palette",
    rules: ["Any design tool allowed", "Present your design", "User flow required"],
  },
  {
    name: "Tech Quiz",
    description: "Test your knowledge across tech domains — programming, hardware, OS, networking, and more.",
    category: "tech",
    minTeamSize: 1,
    maxTeamSize: 2,
    isActive: true,
    icon: "Brain",
    rules: ["Multiple rounds", "MCQ + Rapid fire", "No electronic devices"],
  },
];

export const DUMMY_ORGANIZERS: Omit<Organizer, "id">[] = [
  { name: "Rahil Khan", role: "Lead Organizer", phone: "+91 9876543210", email: "rahil@kratos.dev" },
  { name: "Priya Sharma", role: "Technical Head", phone: "+91 9876543211", email: "priya@kratos.dev" },
  { name: "Arjun Patel", role: "Event Coordinator", phone: "+91 9876543212", email: "arjun@kratos.dev" },
  { name: "Sneha Reddy", role: "Design Lead", phone: "+91 9876543213", email: "sneha@kratos.dev" },
  { name: "Vikram Singh", role: "Sponsorship Head", phone: "+91 9876543214", email: "vikram@kratos.dev" },
  { name: "Ananya Gupta", role: "PR & Marketing", phone: "+91 9876543215", email: "ananya@kratos.dev" },
];

export const DUMMY_SCHEDULE: Omit<ScheduleSlot, "id">[] = [
  { day: 1, time: "09:00 AM", eventName: "Registration & Check-in", venue: "Main Hall", description: "Collect your badges and event kits" },
  { day: 1, time: "10:00 AM", eventName: "Inauguration Ceremony", venue: "Auditorium", description: "Opening ceremony with chief guests" },
  { day: 1, time: "11:00 AM", eventName: "Code Clash", venue: "Lab 1", description: "Competitive programming begins" },
  { day: 1, time: "11:00 AM", eventName: "UI/UX Challenge", venue: "Lab 2", description: "Design challenge starts" },
  { day: 1, time: "12:00 PM", eventName: "Tech Quiz - Round 1", venue: "Room 301", description: "Prelims" },
  { day: 1, time: "01:00 PM", eventName: "Lunch Break", venue: "Cafeteria", description: "Food and networking" },
  { day: 1, time: "02:00 PM", eventName: "Web Wizards", venue: "Lab 1", description: "Web development sprint" },
  { day: 1, time: "02:00 PM", eventName: "Debug Duals", venue: "Lab 3", description: "Bug fixing competition" },
  { day: 1, time: "04:00 PM", eventName: "Valorant Showdown - Qualifiers", venue: "Gaming Zone", description: "First-round matches" },
  { day: 2, time: "09:30 AM", eventName: "Circuit Quest", venue: "HW Lab", description: "Hardware challenge begins" },
  { day: 2, time: "09:30 AM", eventName: "Robo Race - Trials", venue: "Ground Floor", description: "Time trials and qualifiers" },
  { day: 2, time: "11:00 AM", eventName: "BGMI Battle", venue: "Gaming Zone", description: "Battle Royale tournament" },
  { day: 2, time: "11:00 AM", eventName: "Tech Quiz - Finals", venue: "Auditorium", description: "Final round" },
  { day: 2, time: "01:00 PM", eventName: "Lunch Break", venue: "Cafeteria", description: "Food and networking" },
  { day: 2, time: "02:00 PM", eventName: "Valorant Showdown - Finals", venue: "Gaming Zone", description: "Championship matches" },
  { day: 2, time: "02:00 PM", eventName: "Robo Race - Finals", venue: "Ground Floor", description: "Final race" },
  { day: 2, time: "04:00 PM", eventName: "Valedictory & Prize Distribution", venue: "Auditorium", description: "Awards and closing ceremony" },
];
